name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Run end-to-end tests
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        run: yarn test:e2e
